name: Destroy EKS Cluster
on:
  workflow_dispatch:
jobs:
  destroy-cluster:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Initialize Terraform
        run: terraform init

      - name: Destroy Terraform configuration
        run: terraform destroy -auto-approve   